TRAIN:
    workers: 3


    momentum: 0.9
    weight_decay: 0.00005

    net_type : regular
    channels : 109

    K : 4
    P : 0.75
    seed : 1

    print_freq: 100
    model_dir: model


TEST:
    checkpoint_path : data/pretrained_model/regular_c109_n32.pth
